include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - unnecessary_null_checks
    - require_trailing_commas

metrics:
  cyclomatic-complexity: 20
  lines-of-code: 200
  number-of-methods: 10

rules:
  - avoid-nested-code-blocks
  - avoid-throw-in-catch-block
  - no-boolean-literal-compare
